[package]
name = "ox"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"

[[bin]]
name = "ox"
path = "src/main.rs"

[dependencies]
oxidize-core.workspace = true
oxidize-index.workspace = true
oxidize-refs.workspace = true
oxidize-diff.workspace = true
oxidize-pack.workspace = true
oxidize-transport.workspace = true
oxidize-config.workspace = true
oxidize-tui.workspace = true

clap.workspace = true
clap_complete.workspace = true
anyhow.workspace = true
thiserror.workspace = true
chrono.workspace = true
sha1.workspace = true
rayon.workspace = true

[dev-dependencies]
tempfile.workspace = true
