[package]
name = "oxidize-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oxidize-core.workspace = true
oxidize-index.workspace = true
oxidize-refs.workspace = true
oxidize-diff.workspace = true
oxidize-pack.workspace = true
chrono.workspace = true
thiserror.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[dev-dependencies]
tempfile.workspace = true
